# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='text_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
